"""add bill_events table

Revision ID: c889d199265f
Revises: a1b2c3d4e5f6
Create Date: 2026-07-13 10:42:46.075765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c889d199265f'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('created', 'updated', 'notes_changed', 'enabled', 'disabled', 'cycle_marked_paid', 'cycle_marked_unpaid', 'cycle_amount_changed', 'cycle_notes_changed', name='bill_event_type'), nullable=False),
    sa.Column('cycle_start_date', sa.Date(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_events_account_id'), 'bill_events', ['account_id'], unique=False)
    op.create_index(op.f('ix_bill_events_bill_id'), 'bill_events', ['bill_id'], unique=False)
    op.create_index(op.f('ix_bill_events_created_at'), 'bill_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_events_created_at'), table_name='bill_events')
    op.drop_index(op.f('ix_bill_events_bill_id'), table_name='bill_events')
    op.drop_index(op.f('ix_bill_events_account_id'), table_name='bill_events')
    op.drop_table('bill_events')
    # Postgres enum types survive drop_table (see 9f979f5fb842's downgrade) -
    # drop it explicitly or a re-upgrade would fail with "type already exists".
    sa.Enum(name='bill_event_type').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
