"""add cycle_overrides table

Revision ID: f7442af7b00b
Revises: 12aa348bb14f
Create Date: 2026-07-12 19:10:49.028339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7442af7b00b'
down_revision: Union[str, Sequence[str], None] = '12aa348bb14f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('windfall_id', sa.Integer(), nullable=True),
    sa.Column('cycle_start_date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('override_amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(bill_id IS NULL) != (windfall_id IS NULL)', name='ck_cycle_overrides_exactly_one_target'),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['windfall_id'], ['windfalls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'bill_id', 'cycle_start_date', name='uq_cycle_overrides_bill_cycle'),
    sa.UniqueConstraint('account_id', 'windfall_id', 'cycle_start_date', name='uq_cycle_overrides_windfall_cycle')
    )
    op.create_index(op.f('ix_cycle_overrides_account_id'), 'cycle_overrides', ['account_id'], unique=False)
    op.create_index(op.f('ix_cycle_overrides_bill_id'), 'cycle_overrides', ['bill_id'], unique=False)
    op.create_index(op.f('ix_cycle_overrides_windfall_id'), 'cycle_overrides', ['windfall_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cycle_overrides_windfall_id'), table_name='cycle_overrides')
    op.drop_index(op.f('ix_cycle_overrides_bill_id'), table_name='cycle_overrides')
    op.drop_index(op.f('ix_cycle_overrides_account_id'), table_name='cycle_overrides')
    op.drop_table('cycle_overrides')
    # ### end Alembic commands ###
