name: 'Setup Terraform Environment'
description: 'Common setup steps for Terraform workflows with consistent action versions'

inputs:
  aws-role-arn:
    description: 'AWS IAM role ARN for OIDC authentication'
    required: true
  aws-region:
    description: 'AWS region'
    required: false
    default: 'us-west-2'
  terraform-version:
    description: 'Terraform version to install'
    required: false
    default: 'latest'
  terraform-wrapper:
    description: 'Whether to install a wrapper to wrap subsequent calls'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for Terraform commands'
    required: false
    default: './infra'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Configure AWS credentials
      if: ${{ !env.ACT }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: ${{ inputs.terraform-wrapper }}
        
    - name: Cache Terraform providers
      uses: actions/cache@v4
      with:
        path: ${{ inputs.working-directory }}/.terraform
        key: terraform-${{ hashFiles(format('{0}/.terraform.lock.hcl', inputs.working-directory)) }}
        restore-keys: |
          terraform-