name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # IMPORTANT: "backend-test" and "frontend-test" are required status checks for PRs
  # Do not rename these jobs without updating branch protection rules
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Test
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --all-extras
          poetry run pytest
  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: ./frontend/.nvmrc
      - name: Test
        run: |
          yarn install --frozen-lockfile
          yarn test
