<script lang="ts">
	const lastUpdated = 'July 13, 2026';
</script>

<h1 class="text-2xl font-semibold text-text">Privacy Policy</h1>
<p class="mt-1 text-sm text-slate-500">Last updated: {lastUpdated}</p>

<div class="mt-6 flex flex-col gap-6 text-sm leading-relaxed text-slate-700">
	<p>
		Tally ("Tally", "we", "us") is a bill-tracking and balance-forecasting tool. This policy
		explains what information we collect, how we use it, and the choices you have. It applies
		to the Tally web application only.
	</p>

	<section>
		<h2 class="text-base font-semibold text-text">Information we collect</h2>
		<ul class="mt-2 list-disc space-y-1 pl-5">
			<li>
				<strong>Account information.</strong> When you sign up, our authentication provider (Auth0)
				shares your email address and a unique identifier with us so we can associate your data with
				your account.
			</li>
			<li>
				<strong>Financial data you enter.</strong> Bank account nicknames and institutions, recurring
				bill names/amounts/schedules, one-off transactions, and windfalls - all typed in directly by
				you. Tally does not connect to real bank accounts, does not use a service like Plaid to read
				live transactions, and never collects account numbers, routing numbers, or banking credentials.
				Everything you see reflects data you entered yourself, not a live feed from your bank.
			</li>
			<li>
				<strong>Usage data.</strong> Standard server logs (timestamps, IP address, request paths)
				generated by our hosting infrastructure for security and debugging purposes.
			</li>
		</ul>
	</section>

	<section>
		<h2 class="text-base font-semibold text-text">How we use this information</h2>
		<ul class="mt-2 list-disc space-y-1 pl-5">
			<li>To provide the forecasting and bill-tracking features you use Tally for.</li>
			<li>To authenticate you and keep your account secure.</li>
			<li>To diagnose and fix technical problems.</li>
			<li>To communicate with you about your account, if needed.</li>
		</ul>
		<p class="mt-2">
			We do not sell your personal information, and we do not use it for advertising or share it
			with data brokers.
		</p>
	</section>

	<section>
		<h2 class="text-base font-semibold text-text">Who we share it with</h2>
		<p class="mt-2">
			We use a small number of service providers to run Tally, each of which processes data on
			our behalf under its own privacy policy:
		</p>
		<ul class="mt-2 list-disc space-y-1 pl-5">
			<li><strong>Auth0</strong> - authentication and login.</li>
			<li><strong>Amazon Web Services (AWS)</strong> - application hosting (Lambda, CloudFront, S3).</li>
			<li><strong>Neon</strong> - our PostgreSQL database provider, where your data is stored.</li>
		</ul>
		<p class="mt-2">
			We do not otherwise share your information with third parties, except where required by
			law.
		</p>
	</section>

	<section>
		<h2 class="text-base font-semibold text-text">Cookies and local storage</h2>
		<p class="mt-2">
			Tally and Auth0 use cookies and browser local storage only as needed to keep you signed in
			between visits. We don't use tracking or advertising cookies.
		</p>
	</section>

	<section>
		<h2 class="text-base font-semibold text-text">Your choices</h2>
		<ul class="mt-2 list-disc space-y-1 pl-5">
			<li>You can export your bill data as a CSV at any time from an account's Bills page.</li>
			<li>You can delete individual bills, transactions, windfalls, or accounts from within the app.</li>
			<li>
				To request a full export or deletion of your account and all associated data, contact us
				(below) and we'll handle it promptly.
			</li>
		</ul>
	</section>

	<section>
		<h2 class="text-base font-semibold text-text">Children's privacy</h2>
		<p class="mt-2">
			Tally is not directed at children under 13, and we do not knowingly collect information from
			them.
		</p>
	</section>

	<section>
		<h2 class="text-base font-semibold text-text">Changes to this policy</h2>
		<p class="mt-2">
			If we make material changes to this policy, we'll update the "Last updated" date above and,
			where appropriate, notify you in the app.
		</p>
	</section>

	<section>
		<h2 class="text-base font-semibold text-text">Contact us</h2>
		<p class="mt-2">
			Questions about this policy or your data? Email
			<a class="text-primary underline" href="mailto:privacy@tally.dev">privacy@tally.dev</a>.
		</p>
	</section>
</div>
